version: '3'
volumes:
  pgdata:
  static_files:
services:
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=personal_website.settings.prod
      - PYTHONUNBUFFERED=1
    volumes:
      - static_files:/static_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 personal_website.wsgi -b 0.0.0.0:8000
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 80:80
